name: CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      run: |
        sudo apt update
        sudo apt install cmake pkg-config clang-15 lld-15
        sudo apt install build-essential autoconf libtool yasm nasm
        sudo apt install smpq gperf pkgconf libarchive-tools autopoint po4a git curl doxygen
        sudo apt install makepkg pacman-package-manager

    - name: Build SDK
      run: bash ci.sh

    - name: Package SDK
      run: tar -czf ps5-payload-dev.tar.gz -C / opt/ps5-payload-sdk

    - name: Upload SDK
      uses: actions/upload-artifact@v3
      with:
        name: ps5-payload-dev
        path: ./ps5-payload-dev.tar.gz
        if-no-files-found: error

    - name: Upload Payload Daemons
      uses: actions/upload-artifact@v3
      with:
        name: ps5-payload-daemons
        path: /opt/ps5-payload-sdk/target/user/homebrew/sbin/*.elf
        if-no-files-found: error
